### ISSUE TITLE
replicating pydot graph objects

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pydot#101]
I use the following script to create a digraph:

`G = pydot.Dot(graph_type = 'digraph')`

Then create a copy of `G`:

`G_decomp = G`

I did some changes on the node/edge-properties of `G_decomp`.

Also created another copy of `G`:

`G_MM = G`

Here is the issue: when I change the properties of `G_decom`, it also change `G`.
How to this problem? `G_decomp = G` doesn't create an independent copy of `G`. I 
found that in `networkx`, there is function to replicate graphs -- `Gnx.copy()`
where `Gnx` is `networkx` graph instance. 

Original issue reported on code.google.com by `anushka....@gmail.com` on 10 Apr 2015 at 12:25

**Comment by johnyf** [comment]
Please read the [documentation](https://docs.python.org/3.5/library/copy.html) for the `copy` module from the standard library: in python, assignment creates a new pointer to the object, not a new instance of an object.

Please consider using the function [`copy.deepcopy`](https://docs.python.org/3.5/library/copy.html#copy.deepcopy). As of b835fb1c532f73d8ae0ea4d9d18052489cdb8f93 , classes in the `pydot` module don't have methods for copying. I see little motivation in introducing methods dedicated to this purpose, because they will essentially use `copy.deepcopy`, unless the code is refactored first.
