### ISSUE TITLE
compatibility with python 2.6?

### ISSUE THREAD

**Issue by fvisin** [erocarrera/pydot#123]
`pip install pydot` fails on python 2.6 with the following error:

> Downloading pydot-1.2.2.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 20, in <module>
>       File "/tmp/pip-build-XC6efm/pydot/setup.py", line 7, in <module>
>         import pydot
>       File "pydot.py", line 1832
>         default_names = {'dot', 'twopi', 'neato',
>                           ^
> SyntaxError: invalid syntax

**Comment by johnyf** [comment]
Thanks for reporting this incompatibility with Python 2.6, introduced in bc639e76b214b1795ebd6263680ee55d9d4fca9f. It is due to the syntax for set literals introduced in Python 3 and [backported to Python 2.7](https://docs.python.org/3/whatsnew/2.7.html#python-3-1-features). I would strongly recommend upgrading to Python 2.7, if possible.

I am wiling to use the syntax `set([...])` at this place. But I do not plan to make a conscious effort for maintaining backward compatibility with Python < 2.7. The last planned release of Python 2 happened a few days ago, and its end of life is 2020, as planned in [PEP 373](http://legacy.python.org/dev/peps/pep-0373/).

**Comment by fvisin** [comment]
Thank you for the quick response and for your availability in fixing the bug. 
We will consider dropping support to Python 2.6 in Theano too, but it might not happen in the near future. In any case, I perfectly understand why you don't plan to actively support Python 2.6 anymore.

**Comment by johnyf** [comment]
Fixed by 95a32c3dda4d7f0962d51bddbd103ca988affd0d.
For posterity, all tests passed with python 2.6 on Travis CI on a branch named `travis`, [log here](https://travis-ci.org/erocarrera/pydot/jobs/143507934).

**Comment by fvisin** [comment]
Great thanks!
