### ISSUE TITLE
install pydot using conda

### ISSUE THREAD

**Issue by stepseazy** [erocarrera/pydot#154]
Hey I get this error when installing, how do I get around this? Thanks:
```

conda install pydot
Fetching package metadata .........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - pydot -> pyparsing 1.5.6 -> python 3.3*
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by johnyf** [comment]
`pydot == 1.2.3` (latest release) [requires `pyparsing >= 2.1.4`](https://github.com/erocarrera/pydot/blob/ae51c606731cebfe5cddc13528f65acd3ceea9f6/setup.py#L34). `pyparsing == 2.2.0` [appears to](https://pypi.org/project/pyparsing/#description) support Python 2.6, 2.7, 3.3, 3.4, 3.5. So the above conflict probably arises due to some dependency pinned to `pydot == 1.0.29`, which [required `pyparsing == 1.5.7`](https://github.com/erocarrera/pydot/blob/e80f9055d19c630cd21b6cffb900f92a3a477a0f/setup.py#L30) (due to `pyparsing` breaking backward compatibility in later versions). Also, `pyparsing == 1.5.6` [appears to](https://pypi.org/project/pyparsing/1.5.6/) support Python 3 but not Python 2, and `pyparsing == 1.5.7` [appears to](https://pypi.org/project/pyparsing/1.5.7/) support Python 2 but not Python 3.

This is why `pydot == 1.1.0` was a compatibility update that left the API almost unchanged, and [works with `pyparsing >= 1.5.7`](https://github.com/erocarrera/pydot/blob/35a8d858bd9da0b37268fe9b317fe4895387e75f/ChangeLog#L55).

So I would suggest finding which package has pinned `pydot` to 1.0.29, and using 1.1.0 or a later version instead.
