### ISSUE TITLE
Why do you violate the constraints and use to_string (your self-invented name) instead of __str__ (the magic method name for converting to a string) ?

### ISSUE THREAD

**Issue by KOLANICH** [erocarrera/pydot#155]
It's very surprising. I had to dig into the library internals to get the source without dot executable. Also I think that dot executable should not be called at all when the output format is ```dot```.

**Comment by johnyf** [comment]
The `to_string` methods were introduced some time ago, in https://github.com/erocarrera/pydot/commit/c0233c6aae32d11d2dc1e0f836c0bcf8b2fab6d0#diff-44fda7721399b25e8cb06471016a3454R485.  One motivation for not implementing `__str__` could be considering the conversion to string as a transformation to an output format, instead of the "string representation" of the constructs. Documenting this method in a tutorial would be one way to point at it. Another possible change is to implement `__str__`, though not sure whether this aligns with the original design intent.

**Comment by johnyf** [comment]
The method [`pydot.Graph.to_string`](https://github.com/erocarrera/pydot/blob/35a8d858bd9da0b37268fe9b317fe4895387e75f/pydot.py#L1432) does not call the `dot` executable, it works in pure Python.

The method [`pydot.Dot.write_dot`](https://github.com/erocarrera/pydot/blob/35a8d858bd9da0b37268fe9b317fe4895387e75f/pydot.py#L1745) does [call](https://github.com/erocarrera/pydot/blob/35a8d858bd9da0b37268fe9b317fe4895387e75f/pydot.py#L1774) the `dot` executable. The reason is that `dot` computes a layout for the graph, and the resulting file contains coordinate information (which can be useful to other tools, for example for translating to LaTeX).
For example, `to_string` can give:

```python
'strict graph G {\n1;\n2;\n1 -- 2;\n}\n'
```

and for the same graph `write_dot` dumps:

```dot
strict graph G {
	graph [bb="0,0,54,108"];
	node [label="\N"];
	1	 [height=0.5,
		pos="27,90",
		width=0.75];
	2	 [height=0.5,
		pos="27,18",
		width=0.75];
	1 -- 2	 [pos="27,71.697 27,60.846 27,46.917 27,36.104"];
}
```

**Comment by KOLANICH** [comment]
Thank you for the answer. I vote for implementing __str__.
