### ISSUE TITLE
Python 3: pydot.py, line 1498, in to_string: obj_list.sort(); TypeError: unorderable types: dict() < dict()

### ISSUE THREAD

**Issue by elistevens** [erocarrera/pydot#158]
Under python3, I get the following:
```python
Traceback (most recent call last):
  File "images/p2overview.py", line 140, in <module>
    print(graph.to_string())
  File "/mnt/c/Users/elis/linux-home/edit/book/.venv/lib/python3.5/site-packages/pydot.py", line 1530, in to_string
    graph.append( sgraph.to_string()+'\n' )
  File "/mnt/c/Users/elis/linux-home/edit/book/.venv/lib/python3.5/site-packages/pydot.py", line 1498, in to_string
    obj_list.sort()
TypeError: unorderable types: dict() < dict()
```

Adding this debugging code:
```python
        try:
            obj_list.sort()
        except:
            print(repr(self))
            for x in sorted(obj_list, key=repr): print(repr(x), '\n')
            raise
```

Results in this output:
```python
<pydot.Subgraph object at 0x7f0e796211d0>
(1, {'sequence': 1, 'port': None, 'name': 'Ct', 'parent_graph': <pydot.Dot object at 0x7f0e79772f28>, 'type': 'node', 'attributes': {'shape': 'box3d', 'label': 'Ct'}, 'parent_node_list': None})

(1, {'sequence': 1, 'port': None, 'name': 'cache_dir', 'parent_graph': <pydot.Dot object at 0x7f0e79772f28>, 'type': 'node', 'attributes': {'shape': 'cylinder', 'label': 'Cache Dir\\n(.pkl.gz)'}, 'parent_node_list': None})

(2, {'sequence': 2, 'port': None, 'name': 'getCtInputChunk', 'parent_graph': <pydot.Dot object at 0x7f0e79772f28>, 'type': 'node', 'attributes': {'shape': 'rect', 'label': '@disk_cache\\ngetCtInputChunk'}, 'parent_node_list': None})

(4, {'sequence': 4, 'port': None, 'name': 'LunaDataset', 'parent_graph': <pydot.Dot object at 0x7f0e79772f28>, 'type': 'node', 'attributes': {'shape': 'box3d', 'label': 'LunaDataset'}, 'parent_node_list': None})
```

The problem seesm to go away if I change the `obj_list.sort()` line to `obj_list.sort(key=lambda o: (o[0], o[1].get('name', None), repr(o)))`.

Thanks for taking a look.

**Comment by elistevens** [comment]
Dict sorting changed in python 3: https://stackoverflow.com/questions/22333388/dicts-are-not-orderable-in-python-3

**Comment by johnyf** [comment]
I could reproduce this error outside `pydot`, by creating a `list` with the contents reported [above](https://github.com/erocarrera/pydot/issues/158#issue-254847824) (using Python 3.5.2rc1+). I could not reproduce the error from within `pydot`. From a first inspection, it appears impossible to create this bug by using the method `pydot.Graph.add_node`, because it assigns a unique sequence number to each node (strictly increasing numbers):

https://github.com/erocarrera/pydot/blob/35a8d858bd9da0b37268fe9b317fe4895387e75f/pydot.py#L1115

https://github.com/erocarrera/pydot/blob/35a8d858bd9da0b37268fe9b317fe4895387e75f/pydot.py#L1077-L1083

https://github.com/erocarrera/pydot/blob/35a8d858bd9da0b37268fe9b317fe4895387e75f/pydot.py#L908

It would be interesting if you could provide details about how this graph was created. The error is caused by the sequence number 1 occurring in both node `Ct` and node `cache_dir`. But that coincidence is impossible to obtain via the method `add_node`, because the value of `'current_child_sequence'` changes at only the two lines cited above. One would have to modify `'current_child_sequence'` directly in order to create this state.

In any case, in order to avoid such an error in case of modifying the graph directly, the `key` argument of the method [`list.sort`](https://docs.python.org/3.7/library/stdtypes.html#list.sort) will be used.

For anyone interested in reproducing the error in isolation:

```python
import pydot

g = pydot.Dot()

t = [
(1, {'sequence': 1, 'port': None, 'name': 'Ct', 'parent_graph': g, 'type': 'node', 'attributes': {'shape': 'box3d', 'label': 'Ct'}, 'parent_node_list': None}),
(1, {'sequence': 1, 'port': None, 'name': 'cache_dir', 'parent_graph': g, 'type': 'node', 'attributes': {'shape': 'cylinder', 'label': 'Cache Dir\\n(.pkl.gz)'}, 'parent_node_list': None}),
(2, {'sequence': 2, 'port': None, 'name': 'getCtInputChunk', 'parent_graph': g, 'type': 'node', 'attributes': {'shape': 'rect', 'label': '@disk_cache\\ngetCtInputChunk'}, 'parent_node_list': None}),
(4, {'sequence': 4, 'port': None, 'name': 'LunaDataset', 'parent_graph': g, 'type': 'node', 'attributes': {'shape': 'box3d', 'label': 'LunaDataset'}, 'parent_node_list': None})]

t.sort()
```

Changing the second item to `(3, {'sequence': 1, 'port': None, 'name': 'cache_dir', 'parent_graph': g, 'type': 'node', 'attributes': {'shape': 'cylinder', 'label': 'Cache Dir\\n(.pkl.gz)'}, 'parent_node_list': None})` avoids this error.

Sidenote: I would recommend not using the letter `o` as an identifier. Cf also [PEP8: "Names to Avoid"](https://www.python.org/dev/peps/pep-0008/#names-to-avoid).

**Comment by elistevens** [comment]
I believe that this is the code that produced the output in question:

[p2overview.py.txt](https://github.com/erocarrera/pydot/files/1592091/p2overview.py.txt)

I've since moved on, though, so I'm not 100% certain that this is the right commit.
