### ISSUE TITLE
please remove CRLF and replace them with LF in 3 test files

### ISSUE THREAD

**Issue by sandrotosi** [erocarrera/pydot#163]
hello,
the following test files contain CRLF, which tend to play badly with git on non-windows system (as it will replace them with simple LF)

```
 pydot-1.2.3/test/graphs/b545.dot
 pydot-1.2.3/test/graphs/b993.dot
 pydot-1.2.3/test/graphs/cairo.dot
```

can you please replace CRLF with LF in them (as in all the other test files)?

thanks!

**Comment by johnyf** [comment]
Was there some particular error?

On Travis CI, `pydot` [uses Ubuntu](https://travis-ci.org/erocarrera/pydot/jobs/292140766#L18). There are no issues with these files there. The presence of CRLF in these files is likely intentional, in order to test `pydot` with input that it would get in Windows environments.

With:

https://github.com/erocarrera/pydot/blob/35a8d858bd9da0b37268fe9b317fe4895387e75f/.gitattributes#L2

and the default value `core.autocrlf=false` I think that these files would be checked out with LF line endings. On my machine I have `core.autocrlf=input`, so these files are checked out with CRLF line endings.

**Comment by sandrotosi** [comment]
yeah the problem is that we maintain the debian packaging for pydot in git, and we import the source code from tarball as-is, but once you import it in git those CRLF will get converted to LF making the source code different from what's in the tarball from GH, causing a failure to build

**Comment by johnyf** [comment]
Could you please mention the error message or kind of failure?

If I change the line endings of those files to LF, the tests run as normal (locally).
About packaging, maybe using `git-submodule` could be useful.

For posterity, on Travis CI the files mentioned [above](https://github.com/erocarrera/pydot/issues/163#issue-276772164) have CRLF line endings.

**Comment by johnyf** [comment]
Although this situation does not raise any errors as far as the tests are concerned (at least on Travis CI, and for me locally), the `git` repository is in an "unstable" state, in that cloning without other actions leaves the repository in a state that `git` thinks files have changed. For more details see [here](https://stackoverflow.com/a/47493057/1959808). The best option appears to be to commit the files mentioned above with LF line endings.

**Comment by sandrotosi** [comment]
yes that's exactly what i see - thanks for looking into that!

**Comment by sandrotosi** [comment]
thanks a lot, much appreciated!
