### ISSUE TITLE
allow tests to be executed from any directory [PATCH]

### ISSUE THREAD

**Issue by sandrotosi** [erocarrera/pydot#164]
Hello,
i've applied this patch to pydot debian package so taht we can run pydot_unittest.py from any directory:

```
diff --git a/test/pydot_unittest.py b/test/pydot_unittest.py
index 97e252a..1e3a3cb 100644
--- a/test/pydot_unittest.py
+++ b/test/pydot_unittest.py
@@ -20,7 +20,7 @@ import unittest
 
 
 DOT_BINARY_PATH         = 'dot'
-TEST_DIR                = './'
+TEST_DIR                = os.path.dirname(sys.argv[0])
 REGRESSION_TESTS_DIR    = os.path.join(TEST_DIR, 'graphs')
 MY_REGRESSION_TESTS_DIR    = os.path.join(TEST_DIR, 'my_tests')
```

could you include it upstream?

thanks!

**Comment by johnyf** [comment]
Was this intended to be `argv[1]`? From the [documentation](https://docs.python.org/3.7/library/sys.html#sys.argv):

>  `sys.argv`
>
> The list of command line arguments passed to a Python script. `argv[0]` is the script name (it is operating system dependent whether this is a full pathname or not). If the command was executed using the `-c` command line option to the interpreter, `argv[0]` is set to the string `'-c'`. If no script name was passed to the Python interpreter, `argv[0]` is the empty string.

**Comment by sandrotosi** [comment]
nope, it's really argv[0]: you'll get the directory pydot_unittest.py is, and so all the subdirectories will be relative to that, not to ./ which is only local to where i'm python /path/to/pydot_unittest.py

**Comment by johnyf** [comment]
I see. It seems that whether relative or absolute, this would locate the tests. However, if `pydot_unittest.py` is run from `test/..`, then `test/../pydot.py` will run, instead of the files installed in `site-packages` (so the installation won't be tested). Similar: https://github.com/erocarrera/pydot/pull/137#issuecomment-253400453 (using `__file__` in that case).

**Comment by sandrotosi** [comment]
if you want to be extra-sure to select a given installation of the python files, i think the only real way is to set PYTHONPATH (which is what we do when we run pydot test in the debian pkg)

**Comment by johnyf** [comment]
The issue:

```python
git clone git@github.com:erocarrera/pydot
cd pydot
ipython
import pydot
<module 'pydot' from '/path/to/repo/pydot/pydot.py'>
```

This relative import is undesired. It does not happen from outside the repository, nor from inside the directory `test/`. I first encountered this problem on Travis CI (I think with more than one package):

- it happens silently
- can take years to cause some problem, if ever
- does not test the installed package, which is undesired

The last point can be a problem whenever the installation process isn't trivial. For this reason, I am inclined to raise an error if the relative path is `test/`. This would work from directories above, and from within `test/`. But it seems clumsy.

Setting `PYTHONPATH` might be another option, though I prefer not changing the environment when possible.

The approaches I lean towards are:

1. `cd` to `test/` and back when testing the Debian package. If the path to the `pydot_unittest.py` is known, then this seems possible, or

2. offer an optional command line argument of `pydot_unittest.py` via `argparse`, which will be the path to the tests. This is essentially equivalent to the previous, in that one has to use the path twice on the same invocation: `python /some/path/pydot_unittest.py --test_dir=/some/path`.

What I am trying to avoid is implicit path changes by the file itself (PEP 20). Explicitly passing a path should be fine, because then running `pydot_unittest.py` from the `pydot` repo top directory will fail, unless the user explicitly passes the path to the tests, in which case they are more aware of what they are doing (plus a `print(pydot)` could be included to remind the user aware of which `pydot.py` is being run).

**Comment by johnyf** [comment]
This is getting a little complex, and over-constraining. The `sys.argv[0]` approach seems practical. Preventing the user from running tests without installing `pydot.py` isn't the objective, rather to prevent this from happening accidentally.

Recognizing whether we invoked `pydot_unittest.py` from the parent of `test/` is rather convoluted: have to compare `os.getcwd` with `sys.argv[0]`. In principle, we could be above the test directory with `pydot.py` absent (somehow deleted), or someone could in theory copy `test/` under `site-packages`, so we are testing the intended installation, or we could be outside the repository and still have a `pydot.py` present in the `cwd`.

So such a check isn't addressing all cases. Thus, making the check more complicated doesn't add much. Instead, a simple check to avoid the one use case that is common and undesired should suffice: to avoid running from the repository or source distribution (i.e., irrespective of whether `.git` is present) when one wants to test the installation of `pydot`, unless explicitly requested.

Such a simple check is whether a `setup.py` is in the `cwd`. If so, then most likely the unintended scenario is happening, so by default raise an error. Otherwise, run the tests located via `sys.argv[0]`. To override the default, provide an argument that skips checking whether `setup.py` is present in the `cwd`.

(About modifying the `PYTHONPATH`, an example from another package is: https://github.com/tulip-control/tulip-control/blob/1a888997a088b4dfba8dba13d99f393cb9662b6e/run_tests.py#L105-L116).

**Comment by johnyf** [comment]
Implemented in 50bd73084a4c400b7790476ab435fdfd42ebd12a.

While implementing this, I had to remove the (new) argument `--no-check` of `pydot_unittest.py` from `sys.argv`, because it caused `unittest` to fail (since this argument is unknown to `unittest`). This interception of arguments is essentially the same use case with: https://github.com/johnyf/dd/blob/8fa0334ce322935cf19f414f613e00e8f1b82a03/setup.py#L112.

This is why I avoid making tests unnecessarily complicated, i.e., [Kernighan's lever](https://en.wikiquote.org/wiki/Brian_Kernighan):

> Everyone knows that debugging is twice as hard as writing a program in the first place. So if you're as clever as you can be when you write it, how will you ever debug it?

**Comment by sandrotosi** [comment]
i think the was it was implemented is not ideal: the code at

```
def check_path():
    not_check = parse_args()
    if not_check:
        return
    assert not os.path.isfile('setup.py'), (
        'running out of source does not '
        'test the installed `pydot`.')
```
is not super-useful: since tests are not installed(when running `setup.py install` or `setup.py build`) the only way to run them is by referring them from the current directory, which obviously triggers that `assert`.

at least in debian, we _do_ test the built module by changing the PYTHONPATH variable to `build/....` so i think the `check_path()` function can be removed without impacting the unittest suite functionality (and improving its usefulness)

**Comment by sandrotosi** [comment]
FTR we're going to remove the call to `check_path()` in `test/pydot_unittests.py` main for debian

**Comment by sandrotosi** [comment]
actually it worked, passing `--no-check` -- all good here, thanks!
