### ISSUE TITLE
How to customize a networkx graph?

### ISSUE THREAD

**Issue by giumas** [erocarrera/pydot#169]
What is the suggested way to customize the visualization of a graph created with `networkx`?

```
import networkx as nx
G = nx.petersen_graph()
pdot = nx.drawing.nx_pydot.to_pydot(G)

# some styling here
# ....

png_path = "test.png"
pdot.write_png(png_path)
```

![test](https://user-images.githubusercontent.com/2849257/38201112-01b565ae-3665-11e8-9035-615eb20694a9.png)

**Comment by johnyf** [comment]
Any attributes available in the Dot language]() are supported, either via the class constructor, or via `set_*` methods, for example:

```python
g = pydot.Dot('bdd', graph_type='digraph')
nd = pydot.Node(name='a', label='Foo', shape='none')
e = pydot.Edge('ab', 'Bar', style='invis')
```

Relevant excerpts from `pydot` docstrings:

https://github.com/erocarrera/pydot/blob/d6ac9e9244d1a882103422ac2b35ceef96f5dfe3/pydot.py#L642-L654

https://github.com/erocarrera/pydot/blob/d6ac9e9244d1a882103422ac2b35ceef96f5dfe3/pydot.py#L840-L852

The above are for setting attributes after calling the method `networkx.drawing.nx_pydot.to_pydot`. I find it more convenient to set attributes before calling `to_pydot`. The function `to_pydot` uses the attributes of nodes and edges of a `networkx` graph to set attributes of the generated `pydot` graph, for example:

```python
g = networkx.Graph()
g.add_node('a', label='Foo', shape='none')
```

This approach is more convenient because it is at a point before conversion, where the same algorithm that created the `networkx` graph can also annotate it. Relevant excerpts from `networkx` docstrings:

https://github.com/networkx/networkx/blob/5cb6e7ecb8faefa459846c6f8f00b884759c76bc/networkx/drawing/nx_pydot.py#L226-L227

https://github.com/networkx/networkx/blob/5cb6e7ecb8faefa459846c6f8f00b884759c76bc/networkx/drawing/nx_pydot.py#L232-L234

This issue is relevant to #141, #130.

**Comment by giumas** [comment]
Thus, if I want to do it after the `to_pydot` call, the suggested way is something like:

```
import random
import networkx as nx
G = nx.petersen_graph()
pdot = nx.drawing.nx_pydot.to_pydot(G)

shapes = ['box', 'polygon', 'ellipse', 'oval', 'circle', 'egg', 'triangle', 'exagon', 'star', ]
colors = ['blue', 'black', 'red', '#db8625', 'green', 'gray', 'cyan', '#ed125b']
styles = ['filled', 'rounded', 'rounded, filled', 'dashed', 'dotted, bold']

for i, node in enumerate(pdot.get_nodes()):
    node.set_label("n%d" % i)
    node.set_shape(shapes[random.randrange(len(shapes))])
    node.set_fontcolor(colors[random.randrange(len(colors))])
    node.set_fillcolor(colors[random.randrange(len(colors))])
    node.set_style(styles[random.randrange(len(styles))])
    node.set_color(colors[random.randrange(len(colors))])

for i, edge in enumerate(pdot.get_edges()):
    edge.set_label("e%d" % i)
    edge.set_fontcolor(colors[random.randrange(len(colors))])
    edge.set_style(styles[random.randrange(len(styles))])
    edge.set_color(colors[random.randrange(len(colors))])

png_path = "test.png"
pdot.write_png(png_path)
```

![test](https://user-images.githubusercontent.com/2849257/38217059-df74b40a-369a-11e8-9c46-42819c194cd6.png)

Correct?

**Comment by johnyf** [comment]
Yes, this is one possible approach.

**Comment by giumas** [comment]
Thanks!
