### ISSUE TITLE
Problem with empty labels

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pydot#63]
What steps will reproduce the problem?
1. Define node with an empty label:
```
node = Node('PROCESS_END', shape='doublecircle', style='filled', label='', width='.15')
```

What is the expected output?

```
PROCESS_END [width=".15", style=filled, shape=doublecircle, label=""];
```

or better:

```
PROCESS_END [width=".15", style="filled", shape="doublecircle", label=""];
```

What do you see instead?
1. I get:

```
PROCESS_END [width=".15", style=filled, shape=doublecircle, label=];
```

2. and the the exception while generating `png` output:

```
Error: XXX.gv:17: syntax error near line 17
context: PROCESS_END [width=".15", style=filled, shape=doublecircle, >>>  
label=] <<< ;
```

3. and the result picture without the requested width of .15, and with a 
`PROCESS_END` label .

What version of the product are you using? On what operating system?
The case is with 1.0.28 release. 

Please provide any additional information below.
Release 1.0.25 manages this case properly.

IMO all the attribute values should be quoted. 

Original issue reported on code.google.com by `rganow...@metoda.com.pl` on 10 Jan 2012 at 9:19

**Comment by johnyf** [comment]
Present as of 3a8ee3d414fbe447af59cce753e71bf2fe050771.
As remarked [above](https://github.com/erocarrera/pydot/issues/63#issuecomment-92396918), setting a node `label=None` works because of [this check](https://github.com/erocarrera/pydot/blob/3a8ee3d414fbe447af59cce753e71bf2fe050771/pydot.py#L619).

Empty labels cause errors with `graphviz version 2.39.20160710.1729 (20160710.1729)` too.
For example:

`Error: /tmp/tmpzhdQqD: syntax error in line 2 near ']'`

Fixed by fd356cfe99e1b706239bab6cc71dfcd77e5c86b4.
