### ISSUE TITLE
pydot can not print graph with special characters

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pydot#86]
The following code shows that `pydot` can't print graph whose nodes consist of special characters. Is it a bug of `pydot`?

```python
import pydot

graph = pydot.Dot(graph_type='graph')
graph.add_edge(pydot.Edge("<a>", "<b>"))
graph.add_edge(pydot.Edge("<a>", "<c>"))
graph.write_png('main1.png')
```

Original issue reported on code.google.com by `PengYu...@gmail.com` on 30 Nov 2013 at 3:00

**Comment by johnyf** [comment]
This is normal GraphViz behavior. From the [DOT language grammar](http://www.graphviz.org/doc/info/lang.html):

```
node_stmt 	: 	node_id [ attr_list ]
node_id 	: 	ID [ port ]
```

and:

"An ID is one of the following:
...
- an HTML string (<...>). "

So, `graph.to_string()` produces:

```python
'graph G {\n<a> -- <b>;\n<a> -- <c>;\n}\n'
```

and these nodes are interpreted by GraphViz as "a", "b", and "c".
In order to get the `<` and `>` symbols to show, you would have to either enclose the node IDs within quotes, as follows:

```python
import pydot

graph = pydot.Dot(graph_type='graph')
graph.add_edge(pydot.Edge('"<a>"', '"<b>"'))
graph.add_edge(pydot.Edge('"<a>"', '"<c>"'))
graph.write_png('main1.png')
```

or define the strings "<a>" etc as node labels.
