### ISSUE TITLE
Make dot_parser import error mutable

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pydot#97]
When you import `pydot` without having `dot_parser` installed, you get a warning 
like this:
```
"Couldn't import dot_parser, loading of dot files will not be possible"
```
Since this warning is output to `stdout`, you can't mute it, so if you don't need 
`dot_parser`, you have a warning you can never silence.

The attached patch replaces the print statement with a call to `warnings.warn()`, 
so that the import warning can be optionally muted.

Original issue reported on code.google.com by `s...@cloudlock.com` on 22 Dec 2014 at 1:49

Attachments:
* [patch.txt](https://storage.googleapis.com/google-code-attachments/pydot/issue-97/comment-0/patch.txt)

**Comment by johnyf** [comment]
In general, I prefer to keep `print` for such warnings, because [by default](https://docs.python.org/2/library/warnings.html#the-warnings-filter) a warning is printed only once, even when not explicitly silenced. Thus, warnings can easily escape attention.

Nonetheless, in this case the warning is anyway to appear only once: at import time. So, if it is to be noticed at all, then that will happen at import time, and not later. In other words, it is not a warning within some function, that would appear upon the first call to that function, but be automatically silenced in later calls, and so be lost inside the rest of the output (and never noticed by the user).

Also, `pydot >= 1.1.0` is compatible with `pyparsing >= 1.5.7` (#81), so this warning shouldn't any more arise frequently in practice.

The patch has been applied in f9646b15d56304826a4ee940544b9b070d3114df.
